server:
  port: 7001
  servlet:
    context-path: /api/v1
# =====================数据源配置===========================
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/showbox?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
     username: root
     password: zhd123456
     driver-class-name: com.mysql.jdbc.Driver

#=========================mybatis=======================     
mybatis:
    mapperLocations: classpath:com/cpjl/api/dao/custom/*.xml
    typeAliasesPackage: com.cpjl.api.entity
#=========================logging=======================     
logging:
   path: D:/cpdata/logs/cpjl-api