server:
  port: 7002
  servlet:
    context-path: /managecenter
    session:
      timeout: 86400s
# =====================数据源配置===========================
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/showbox?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
     username: root
     password: zhd123456
     driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      enabled: false

#=========================mybatis=======================     
mybatis:
    mapperLocations: classpath:com/cpjl/managecenter/dao/custom/*.xml
    typeAliasesPackage: com.cpjl.managecenter.entity
#=========================logging=======================     
logging:
   path: D:/cpdata/logs/cpjl-managecenter